# Generated by Django 2.0.6 on 2018-08-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_robotinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotinfo',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='robot_name'),
        ),
    ]
